/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false workers/zhihu-sync/worker-configuration.d.ts` (hash: a7c15aabb42cac38dfdadab3c6ebbf0c)
interface __BaseEnv_Env {
	ZHIHU_CACHE: KVNamespace;
	ALLOWED_ORIGINS: "https://onfireq.github.io,http://localhost:3000,http://127.0.0.1:3000";
	FOLLOWER_COUNT: "18";
	ZHIHU_API_URL: "https://developer.zhihu.com/api/v1/user/contents";
	ZHIHU_ACCESS_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "FOLLOWER_COUNT" | "ZHIHU_API_URL" | "ZHIHU_ACCESS_SECRET">> {}
}
